events/urls.py
from django.conf.urls import url
from django.views.generic.base import TemplateView

from . import views

app_name = "events"
urlpatterns = [
    url(r'^$', views.ListUserView.as_view(), name="user_list"),
    url(r'^home/$', TemplateView.as_view(template_name='events/index.html'), name="home"),
    url(r'^event-list/$', views.ListEventView.as_view(), name="event_list"),
    url(r'^create-event/$', views.CreateEventView.as_view(), name="create_event"),
    url(r'^event-list/(?P<pk>\d+)/$', views.EventDetailView.as_view(), name="event_details"),

    # url(r'^(?P<pk>\d+)/add-reply/$', views.CreateReplyView.as_view(), name="create_reply"),
    # url(r'^(?P<pk>\d+)/reply_details/$', views.ReplyDetailView.as_view(), name="reply_details"),
    # url(r'^view-singles/$', views.ListsinglesView.as_view(), name="singles_list"),
]

speedateevents/urls.py
# from django.conf.global_settings import MEDIA_URL, MEDIA_ROOT
from django.conf import settings
from django.conf.urls import url, include, patterns
from django.conf.urls.static import static
from django.contrib import admin
from events import views
from speedateevents.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    url(r'', include('events.urls')),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^signup/$', views.CreateUserView.as_view(), name='signup'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^admin/', admin.site.urls),
]  # + static(MEDIA_URL, document_root=MEDIA_ROOT)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
                            (r'^pictures/(?P<path>.*)$', 'django.views.static.serve', {
                                'document_root': settings.MEDIA_ROOT}))

events/models.py
from datetime import date

from django.conf.global_settings import MEDIA_ROOT
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models


class Gender:
    MALE = 1
    FEMALE = 2

    choices = (
        (MALE, 'male'),
        (FEMALE, 'female'),
    )


class Status:
    SINGLE = 1
    DIVORCEE = 2
    DIVORCEE_WITH_KIDS = 3

    choices = (
        (SINGLE, 'single'),
        (DIVORCEE, 'divorcee'),
        (DIVORCEE_WITH_KIDS, 'divorcee with kids'),
    )


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        unique=True,
        on_delete=models.CASCADE, )

    gender = models.IntegerField(choices=Gender.choices)
    status = models.IntegerField(choices=Status.choices, default=Status.SINGLE)
    dob = models.DateField(null=True, blank=True)
    is_cohen = models.BooleanField(default=False)
    picture = models.ImageField(upload_to=MEDIA_ROOT, default=MEDIA_ROOT + '/no-image.jpg')

    # country = models.CharField(max_length=50, null=True, blank=True)
    # address = models.CharField(max_length=100, null=True, blank=True)
    # city = models.CharField(max_length=50, null=True, blank=True)
    # state = models.CharField(max_length=50, null=True, blank=True)

    is_matchmaker = models.BooleanField(default=False)
    is_single = models.BooleanField(default=False)

    def calculate_age(self):
        age = 0
        today = date.today()
        if self.dob:
            age = today.year - self.dob.year - ((today.month, today.day) < (self.dob.month, self.dob.day))
        return age

    def __str__(self):
        return "{}".format(
            self.user.username,
        )


class Event(models.Model):
    owner = models.ForeignKey(Profile)
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    date = models.DateField()
    singles_num = models.IntegerField(default=60)
    singles_approved = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse("events:event_details", args=(self.pk,))

    def __str__(self):
        return "{}".format(
            self.title,
        )

events/forms.py
from django import forms
from django.forms import ModelForm, CharField, EmailField, PasswordInput, models

from . import models


class LoginForm(forms.Form):
    username = forms.CharField(max_length=300)
    password = forms.CharField(max_length=300, widget=forms.PasswordInput())


class SignupForm(ModelForm):
    first_name = CharField(max_length=300)
    last_name = CharField(max_length=300)
    username = CharField(max_length=300)
    password = CharField(max_length=300, widget=PasswordInput())
    password_confirm = CharField(max_length=300, widget=PasswordInput())
    email = EmailField(max_length=300)

    class Meta:
        model = models.Profile
        fields = [
            'first_name',
            'last_name',
            'username',
            'password',
            'password_confirm',
            'email',
            'dob',
            'gender',
            'status',
            'is_cohen',
            'is_matchmaker',
            'is_single',
            'picture',
        ]

# class SignupForm(forms.Form):
#     first_name = forms.CharField(max_length=300)
#     last_name = forms.CharField(max_length=300)
#     username = forms.CharField(max_length=300)
#     password = forms.CharField(max_length=300, widget=forms.PasswordInput())
#     password_confirm = forms.CharField(max_length=300, widget=forms.PasswordInput())
#     email = forms.EmailField(max_length=300)
#     # gender = forms.IntegerField(choices=Gender.choices)
#     gender = forms.ChoiceField(choices=Gender.choices)
#     # status = forms.IntegerField(choices=Status.choices)
#     status = forms.ChoiceField(choices=Status.choices)
#     is_cohen = forms.BooleanField(required=False)
#     is_matchmaker = forms.BooleanField(required=False)
#     is_single = forms.BooleanField(required=False)

events/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.core.urlresolvers import reverse_lazy, reverse
from django.db import IntegrityError
from django.shortcuts import redirect
from django.utils.encoding import escape_uri_path
from django.views.generic import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, FormView
from django.views.generic.list import ListView

# from events.models import Status
from . import forms
from . import models


# TODO - replace inheritance from LoggedInMixin to an existing
class LoggedInMixin:
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            url = reverse("login") + "?from=" + escape_uri_path(request.path)
            return redirect(url)
        return super().dispatch(request, *args, **kwargs)

    pass


class LoginView(FormView):
    page_title = "Login"
    template_name = "login.html"
    form_class = forms.LoginForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('events:user_list')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = authenticate(username=form.cleaned_data['username'],
                            password=form.cleaned_data['password'])

        if user is not None:
            if user.is_active:
                login(self.request, user)

                if self.request.GET.get('from'):
                    return redirect(
                        self.request.GET['from'])  # SECURITY: check path
            else:
                form.add_error(None, "User isn't active anymore - plz contact admin")
                return self.form_invalid(form)
        else:
            form.add_error(None, "username doesn't exist")
            return self.form_invalid(form)
        return redirect('events:user_list')


class CreateUserView(CreateView):
    page_title = "Signup"
    model = models.Profile
    form_class = forms.SignupForm

    success_url = reverse_lazy('events:user_list')

    def form_valid(self, form):
        if form.cleaned_data['password'] != form.cleaned_data.pop('password_confirm'):
            form.add_error(None, "Passwords do not match")
            return self.form_invalid(form)

        is_matchmaker, is_single = form.cleaned_data.pop('is_matchmaker'), form.cleaned_data.pop('is_single')
        if is_matchmaker == is_single:
            form.add_error(None, "User must be a matchmaker or writer (not both).")
            return self.form_invalid(form)
        dob = form.cleaned_data.pop('dob')
        gender = form.cleaned_data.pop('gender')
        status = form.cleaned_data.pop('status')
        is_cohen = form.cleaned_data.pop('is_cohen')
        picture = form.cleaned_data.pop('picture')

        # Add new user instance
        try:
            user = User.objects.create_user(**form.cleaned_data)
            user = authenticate(**form.cleaned_data)
        except IntegrityError:
            form.add_error(None, "The username is already exist, please try another one.")
            return self.form_invalid(form)

        # Add new user to Profile
        p = models.Profile(user=user, )
        p.dob = dob
        p.gender = gender
        p.status = status
        p.is_cohen = is_cohen
        p.is_single = is_single
        p.is_matchmaker = is_matchmaker
        p.picture = picture
        p.full_clean()
        p.save()

        # Login
        if user is not None:
            if user.is_active:
                login(self.request, user)
            else:
                form.add_error(None, "Disabled account")
                return self.form_invalid(form)
            if self.request.GET.get('from'):
                return redirect(
                    self.request.GET['from'])  # SECURITY: check path
            return redirect('events:user_list')

        resp = super().form_valid(form)
        messages.success(self.request, "User created successfully.")
        return resp


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect("login")


class ListUserView(LoggedInMixin, ListView):
    page_title = "Users List"
    model = models.Profile
    paginate_by = 20

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_active and self.request.user.profile.is_single:
            return redirect("events:home")
        return super().dispatch(request, *args, **kwargs)


class CreateEventView(LoggedInMixin, CreateView):
    page_title = "Create an Event"
    model = models.Event
    fields = (
        'title',
        'description',
        'date',
        'singles_num',
    )

    success_url = reverse_lazy('events:event_list')

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.profile.is_single:
            return redirect("/")
        return super().dispatch(request, *args, **kwargs)

    # def get_initial(self):
    #     d = super().get_initial()
    #     d['date'] = datetime.date.today()
    #     return d

    def form_valid(self, form):
        if form.is_valid:
            owner = models.Profile.objects.get(
                user_id=self.request.user.pk)
            form.instance.owner = owner

            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            date = form.cleaned_data['date']
            singles_num = form.cleaned_data['singles_num']

            email_list = []
            for item in models.Profile.objects.all().values('user__email'):
                email_list.append(item['user__email'])

            send_mail(
                title,
                "Hello,\n\n{}\nAt {}\nThe event is only for the first {}  singles only.\nSincerely,\n{}".format(
                    description, date, singles_num, owner),
                'menahem.godick@gmail.com',
                email_list,
                fail_silently=False,
            )

            resp = super().form_valid(form)
            # messages.SUCCESS(self.request, "Event added successfully.") #TODO
        return resp


class ListEventView(LoggedInMixin, ListView):
    page_title = "event list"
    model = models.Event
    paginate_by = 15

    # def get_queryset(self):
    #     try:
    #         if self.request.user.profile.is_matchmaker:
    #             return super().get_queryset().filter(
    #                 owner=models.Profile.objects.get(
    #                     user=self.request.user.pk))
    #     except ObjectDoesNotExist:
    #         print("This user must be a Matchmaker or Single.")


class EventDetailView(LoggedInMixin, DetailView):
    page_title = "event Details"
    model = models.Event

    def dispatch(self, request, *args, **kwargs):
        self.request.session['event_id'] = kwargs['pk']
        return super().dispatch(request, *args, **kwargs)

events/templates/events/event_detail.html
{% extends "base.html" %}

{% block top_link_1 %}
    <a href="{% url "events:event_list" %}">View events</a>
{% endblock %}

{% block top_link_2 %}
    {% if request.user.is_matchmaker %}
            <a href="events:user_list">View Users</a>
    {% elif request.user.is_single %}
            <a href="###">Add Reply</a>
    {% endif %}
{% endblock %}
{% block content %}
    <div class="event_announcement">
        <h1>{{ object.title }}</h1><br/>
        {% if object.description %}
            <h2>{{ object.description|linebreaks }}</h2>
        {% endif %}

        <h3>At {{ object.date }}</h3>
        <h3>The event is only for the first {{ object.singles_num }} singles only.</h3>
    </div>
{% endblock %}

events/templates/events/event_form.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                Save {% bootstrap_icon "save" %}
            </button>
        {% endbuttons %}
    </form>

{% endblock %}

events/templates/events/event_list.html
{% extends "base.html" %}
{% load staticfiles bootstrap3 %}

{% block top_link_2 %}
    {% if request.user.is_matchmaker %}
            <a href="/">View Users</a>
    {% endif %}
{% endblock %}

{% block content %}
    {% bootstrap_messages %}
    {% if object_list %}

        <table class="table table-bordered col-ms-6">
            <thead>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Due Date</th>
                <th>Singles Num</th>
                <th>Singles Approved</th>
                <th>Owner</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <td><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></td>
                    <td>{{ object.description }}</td>
                    <td>{{ object.date }}</td>
                    <td>{{ object.singles_num }}</td>
                    <td>{{ object.singles_approved }}</td>
                    <td>{{ object.owner.user.get_full_name }}</td>
{#                    <td>{{ object.owner.event_user.user.get_full_name }}</td>#}
                </tr>
            {% endfor %}
            </tbody>
        </table>
{% bootstrap_pagination page_obj %}
     {% else %}
        No events Yet.
    {% endif %}
{% endblock %}

events/templates/events/index.html
{% extends "base.html" %}


{% block content %}
<h1>Welcome Home!!</h1>
{% endblock %}

events/templates/events/profile_form.html
{% extends "base.html" %}
{% load bootstrap3 %}
<h1>Signup</h1>

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <ul>
         {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                OK {% bootstrap_icon "OK" %}
            </button>
        {% endbuttons %}
    </ul>
</form>
{% endblock %}

events/templates/events/profile_list.html
{% extends "base.html" %}
{% load staticfiles bootstrap3 %}

{% block top_link_1 %}
    <a href="{% url "events:event_list" %}">View events</a>
{% endblock %}

{% block content %}
    {% bootstrap_messages %}
    {% if object_list %}

            {% for object in object_list %}
                        <a href="{{ object.get_absolute_url }}">
                            <div  class="user_card">
{#                                {% if "http" not in object.picture %} {# TODO CORECT IF#}
{#                                    <img src="{% static object.picture %}" class="img-responsive" alt="image"><br/>#}
{#                                {% else %}#}
                                    <img src="{{ MEDIA_URL }}{{ object.picture }}" class="img-responsive" alt="image"><br/>
{#                                {% endif %}#}
                                Name: {{ object.user }}<br/>
                                Age: {{ object.calculate_age }}<br/>
                                Dob: {{ object.dob }}<br/>
                                Gender: {{ object.get_gender_display }}<br/>
                                Status: {{ object.get_status_display }}<br/>
                                Is Cohen: {{ object.is_cohen|yesno }}<br/>
                            </div>
                        </a>
            {% endfor %}
        {% bootstrap_pagination page_obj %}

    {% else %}
        No users Yet.
    {% endif %}
{% endblock %}

events/templates/events/reply_detail.html
{% extends "base.html" %}

        {% block top_link_1 %}
            <a href="{% url "events:singles_list" %}">Back to all singles</a>
        {% endblock %}
{% block content %}
    <ul class="list-group">
        <br/>
        <p class="event_label">writer:</p>
        <li class="list-group-item">
            {{ object.writer.writer_user.user.get_full_name }}
        </li>
        <br/>
        <p class="event_label">event:</p>
        <li class="list-group-item">
            {{ object.event.title }}
        </li>
        <br/>
        <p class="event_label">status:</p>
        <li class="list-group-item">
            {{ object.get_status_display }}
        </li>
        <br/>
        <p class="event_label">created at:</p>
        <li class="list-group-item">
            {{ object.created_at }}
        </li>
        <br/>
        <p class="event_label">posted at:</p>
        <li class="list-group-item">
            {{ object.posted_at }}
        </li>
        <br/>
        <p class="event_label">reply link:</p>
        <li class="list-group-item">
            {{ object.reply_link }}
        </li>
        <br/>
        <p class="event_label">reply text:</p>
        <li class="list-group-item">
            {{ object.reply_text|linebreaks }}
        </li>
    </ul>
{% endblock %}

events/templates/events/reply_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                Save {% bootstrap_icon "save" %}
            </button>
        {% endbuttons %}
    </form>

{% endblock %}

events/templates/events/user_form.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                Save {% bootstrap_icon "save" %}
            </button>
        {% endbuttons %}
    </form>

{% endblock %}